name: Aqara RocketMQ Bridge
version: 1.1.2
slug: aqara_rocketmq_bridge
description: Aqara RocketMQ bridge for Home Assistant
url: https://github.com/Darkdragon14/aqara-rocketmq-bridge
image: ghcr.io/darkdragon14/aqara-rocketmq-bridge-addon-{arch}
panel_icon: mdi:access-point-network
arch:
  - amd64
  - aarch64
startup: services
init: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Aqara bridge HTTP API
map:
  - homeassistant_config:rw
options:
  app_id: ""
  app_key: ""
  key_id: ""
  bridge_token: ""
  mq_namesrv_addr: "3rd-subscription.aqara.cn:9876"
  bridge_public_url: ""
schema:
  app_id: str
  app_key: password
  key_id: password
  bridge_token: password
  mq_namesrv_addr: str
  bridge_public_url: str
